### ISSUE TITLE
proc_appendChannels: new channel labels not correctly added to clab?

### ISSUE THREAD

**Issue by svendaehne** [bbci/bbci_public#102]
In proc_appendChannels new channel labels are added to the clab cell in the SECOND dimension: 

line 49: dat.clab= cat(2, dat.clab, dat_append.clab);

I.e. if two dats with N1 and N2 channels are merged with this function, the resulting clab has size [N1, N2]. I would however expect it to have size [1, N1+N2]. 

Is this a bug? If not, what is the reason for the behavior?

Also, in line 70 the new labels (if provided) are added like: dat.clab = {dat.clab{:} chanName{:}};
That's different to what happens in line 49

**Comment by BenjaminBlankertz** [comment]
Hm, could it be that your data does not obey the rules of the toolbox? According to the description of the basic data structures channels labels SHOULD be along the second dimension:
  https://github.com/bbci/bbci_public/blob/master/doc/ToolboxData.markdown#Cnt

With respect to line 70, I agree and changed accordingly.

If these remarks resolve the issue, please close it. Otherwise describe what format your input data has.

**Comment by svendaehne** [comment]
My bad, I didn't know about the convention that the labels should be in the second dimension. ;-)
Fixing line 70 closes this issue as far as I am concerned. 
Thanks!
