### ISSUE TITLE
question about train_SWLDAmatlab.m

### ISSUE THREAD

**Issue by manipulative** [bbci/bbci_public#215]
Hello.
I am looking for matlab code about stepwise Linear Discriminant Analysis. And I find bbci_public. It's really a great tool.
But I find it that train_SWLDAmatlab.m use stepwisefit function which of Statistics and Machine Learning Toolbox.
Is stepwisefit function only fit to linear model? Or there are some references support that stepwise function is also fit to LDA?
Looking for your reply.

**Comment by BenjaminBlankertz** [comment]
I do not really understand your question, since LDA is a linear model.
The function train_SWLDAmatlab.m can be used for applications of
stepwise LDA as in the BCI literature.

Best regards,
  Benjamin Blankertz


On 4/13/19 8:06 PM, manipulative wrote:
> Hello.
> I am looking for matlab code about stepwise Linear Discriminant
> Analysis. And I find bbci_public. It's really a great tool.
> But I find it that train_SWLDAmatlab.m use stepwisefit function which of
> Statistics and Machine Learning Toolbox.
> Is stepwisefit function only fit to linear model? Or there are some
> references support that stepwise function is also fit to LDA?
> Looking for your reply.

-- 

Prof. Dr. Benjamin Blankertz

Tel. (+49 30) 314-78626
Fax. (+49 30) 314-75784

Berlin Institute of Technology
Chair for Neurotechnology
Sekr. MAR 4-3, Room 4.041
Marchstr. 23
10587 Berlin
Germany

**Comment by manipulative** [comment]
Thanks for your reply,
I think you are right. I thought that stepwisefit could only be used in general linear model. But I found some reference yesterday say that two classes LDA is very similar to GLM, so it's appropriate to use stepwisefit in LDA.
Thanks for your reply again.
