### ISSUE TITLE
restrain bbci_import_dependencies

### ISSUE THREAD

**Issue by BenjaminBlankertz** [bbci/bbci_public#65]
I would prefer to be asked, whether I want those externals to be downloaded, i.e., make it optional based on user input.

**Comment by JohannesHoehne** [comment]
The problem is that we wanted to prevent some manual "asking-for-input" due to cluster-jobs etc, which may not run then...
How about asking for input once and then writing a file into the /external folder such that all following startups do not ask for input independent on whether or not dependencies were downloaded...
