### ISSUE TITLE
increase visibility and rereference from bbci.de

### ISSUE THREAD

**Issue by JohannesHoehne** [bbci/bbci_public#7]
We should update the bbci.de webpage. When you google "BBCI toolbox", the you land on 
http://bbci.de/toolbox/ which does not reference to github!

**Comment by BenjaminBlankertz** [comment]
Due to the lack of a good documentation there is still no link from bbci.de to 
the toolbox webpage. After generating more demo scripts and some documentation 
at our first hackathon we might do so.

Not sure, what you mean by

> http://bbci.de/toolbox/ which does not reference to github!

The "setup" page does refer to the repository at github. There is a link to the 
github page, but it is unfortunately not formatted as weblink (Basti!).

Benjamin

Am 04.03.2015 um 12:11 schrieb JohannesHoehne:

> We should update the bbci.de webpage. When you google "BBCI toolbox", the zou
> land on
> http://bbci.de/toolbox/ which does not reference to github!

**Comment by venthur** [comment]
I would suggest that after #3 is fixed, we could simply redirect bbci.de/toolbox to the toolbox' github repository or we can get a bit more fancy once #1 is fixed and we redirect to the generated online documentation. The advantage in both cases is, that we can modify the contents of the webpage directly in the toolbox' git repository.

**Comment by venthur** [comment]
bbci.de/toolbox now redirects to the github page.
